### ISSUE TITLE
Cannot find module 'diagnostic-channel'

### ISSUE THREAD

**Issue by clough1** [Microsoft/ApplicationInsights-node.js#256]
I am trying to add application insights to my node/express app. I have applicationinsights v0.20.0 installed and now I am getting this error and my app will not run. I do see the 'diagnostic-channel' folder in that directory so I am not sure why it says it cannot locate it. On previous projects, I did not have this 'diagnostic-channel' when using app insights.  Any thoughts?

```
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'diagnostic-channel'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:4:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by OsvaldoRosado** [comment]
Thanks for reporting this! What versions of Node and NPM are you using? Are you using any libraries that give you an alternative package loader?

**Comment by clough1** [comment]
I am using Node v6.10.1 and NPM v3.10.10.

**Comment by OsvaldoRosado** [comment]
Just to verify, you have applicationinsights in your project.json file and used `npm install` to download it, correct? The resulting node_modules folder structure looks like this as well?
```
node_modules
- applicationinsights
- diagnostic-channel
- diagnostic-channel-publishers
- semver
- zone.js
```

Thanks!

**Comment by clough1** [comment]
I installed it use the npm package manager gui in Visual Studio. It is listed in my package.json file. My node_modules structure:

```
applicationinsights
 - out
  -- AutoCollection
   --- diagnostic-channel
  -- Declarations
  -- Library
  -- TelemetryProcessors
applicationinsights-js
diagnostic-channel
diagnostic-channel-publishers
semver
zone.js
```

**Comment by MSLaguana** [comment]
Can you please double check that there is a `node_modules\diagnostic-channel\package.json` file which is readable, and also a `node_modules\diagnostic-channel\.dist\channel.js` file?

**Comment by clough1** [comment]
Yes, I have both files.

**Comment by OsvaldoRosado** [comment]
I'm noticing that your installation is in `wwwroot`. Do you get this error only when running via IIS (vs local command line)

**Comment by clough1** [comment]
Yes, I am getting the error when trying to access my development/test site. It will work locally.

**Comment by OsvaldoRosado** [comment]
Thanks! It sounds like this might be a permissions or deployment problem. Can you verify that the diagnostic-channel folder on your server has permissions to be read by the user account that runs the service? It might also be worthwhile to check that the files are deployed correctly in the first place. If this is an Azure App Service you can quickly check this with the App Service Editor

![image](https://cloud.githubusercontent.com/assets/4926351/26466424/98a8d0b2-4143-11e7-8483-cf7aeb3a5794.png)

**Comment by clough1** [comment]
I didn't see any issues there. My site is getting ready to go live very soon so I had to reinstall applicationinsights at a lower version. Thanks for your help!

**Comment by OsvaldoRosado** [comment]
I've validated this is working on a clean VS2017 nodejs project, with applicationinsights installed using the VS NPM tooling, and published to an azure app service. Closing for now.

Please feel free to re-open if you run into this again!

**Comment by martincostello** [comment]
I've just had the problem occur updating an AWS Lambda with the ApplicationInsights version changed from `0.19.0` to `0.21.0`:

```
{
  "errorMessage": "Cannot find module 'diagnostic-channel'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:4:28)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/node_modules/applicationinsights/out/applicationinsights.js:2:33)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)"
  ]
}
```

**Comment by SergeyKanzhelev** [comment]
@martincostello [this](https://www.npmjs.com/package/diagnostic-channel) package is a new dependency of Application Insights SDK. Make sure your function is configured correctly and this package can be downloaded

**Comment by fpereira1** [comment]
We've encountered the same issue and it turned out that due to our build process, the [`.dist` folder](https://unpkg.com/diagnostic-channel@0.1.0/.dist/) inside `diagnostic-channel` module was being omitted, that is because by default `grunt-copy` does not copy dot folders.

**Comment by OsvaldoRosado** [comment]
@MSLaguana the `.dist` folder seems to be fairly unreliably deployed given the history of this bug. What do you think of renaming it to no longer being a dot-folder?

**Comment by MSLaguana** [comment]
I have no objection to that; @mike-kaufman / @jackhorton, we can fix this before our next release unless you feel strongly otherwise.

**Comment by mike-kaufman** [comment]
> @MSLaguana the .dist folder seems to be fairly unreliably deployed given the history of this bug. What do you think of renaming it to no longer being a dot-folder?

Hmmm... not following why the dot would impact things.  Is this just a guess or do we understand why the dot in the name is interfering?

**Comment by OsvaldoRosado** [comment]
We have this specific example above in grunt omitting it by default, and the initial example was a case where it worked locally but the folder failed to deploy to the server. The second example, without further investigation, seems to be a lot like the first.

**Comment by jackhorton** [comment]
I think the change is fine. The dot doesn't add much for me, and we were already planning to do a new release soon to publishers to add some new modules.

**Comment by mike-kaufman** [comment]
> We have this specific example above in grunt omitting it by default,

OK, sounds good.

**Comment by iernie** [comment]
We had a similar issue where older nuget (3.x) versions would omit the `.dist` folder during pack. This was fixed for us by upgrading to a newer nuget version (4.x). Writing this here in case somebody else has the same issue we had.

**Comment by OsvaldoRosado** [comment]
I'm not sure this is okay to close until we depend on a newer version of diagnostic-channel

**Comment by AlexBulankou** [comment]
Yes, didn't intend to close.

**Comment by lbochenek** [comment]
Hi @OsvaldoRosado  @AlexBulankou I just encountered this issue with Node v6.9.4, npm v3.10.10, and applicationinsights v1.0.1. My app is running locally, so it can't be a permissions/deploy problem. 

This is the error message:
```
./~/diagnostic-channel/dist/src/channel.js
Module not found: Can't resolve 'module' in 'C:\<path>\node_modules\diagnostic-channel\dist\src'
```

This is my npm node module structure:
```
+-- applicationinsights@1.0.1
| +-- diagnostic-channel@0.2.0
| +-- diagnostic-channel-publishers@0.2.1
| ` -- zone.js@0.7.6
```

The `node_modules\diagnostic-channel\package.json` file is readable, and `node_modules\diagnostic-channel\dist\channel.js` exists. 

Any ideas?

**Comment by larrywal** [comment]
Hi folks - I'm having this same issue following the instructions here: https://docs.microsoft.com/en-us/azure/azure-monitor/learn/nodejs-quick-start

Can someone advise?  I have a Node app with both client and server.  Each have a package.json.

I tried installing applicationinsights-js as well but still get the same issue above.  Can someone help please?
